# https://book.getfoundry.sh/config/hardhat
[default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'

[rpc_endpoints]
ethereum="https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
localhost="http://localhost:8545"
goerli="https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY_GOERLI}"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config